### PR TITLE
init tests

### PR DESCRIPTION
**Pull request by w1kend**
Hello! 👋
By this PR I would like to start adding tests to the project, if you don't mind :)

utils package 0 -> 17% 🎉
`ok      github.com/edoardottt/cariddi/utils     0.209s  coverage: 17.6% of statements`

This if a draft PR, just for example, I'll be updating it.

And some questions
1) Do you want to use any libraries for tests? like https://github.com/stretchr/testify
2) Don't you mind if I make several changes within this PR? as in the first commit - there are some changes for reducing allocations, and simplifying code

### CODE REVIEW

**Comment by edoardottt** [comment]
Hi @w1kend !!

Thanks for the pull request. I'm not ignoring you ahaha I just had to complete the backlog :D

1. It's up to you. You can use the default package or also testify as well.
2. You can make all the changes you want, but try to open a pull request for each file (like this one is for slice.go)

For any question, I hope you know how to reach me :P

**Comment by edoardottt** [comment]
Perfect. Just update your branch with the latest changes I've made (v1.1.8)

**Comment by edoardottt** [comment]
Thanks @w1kend ! Good Job <3

**Comment by w1kend** [comment]
Sure :) I'll add more tests later

**Pull request merged**
